Implement exclude_tags
thegeeklab/prometheus-pve-sd pull request #159
Opened 2022-03-02 20:30 UTC by peschmae

Proxmox 6+ supports tags on VMs, this allows for a neat way to exclude specific vms from prometheus more easily than having to add them to the `exclude_vm` list one by one.

If no tags are set on a VM it's kept in the list.

2022-03-02 21:04 UTC, xoxys requested changes
Thanks. Good improvement. Would you be able to add a test for this exclude option? There is https://github.com/thegeeklab/prometheus-pve-sd/blob/main/prometheuspvesd/test/unit/test_discovery.py#L20 already that might help maybe.

2022-03-02 21:04 UTC, xoxys commented on prometheuspvesd/discovery.py
> +                    .isdisjoint(map(str, self.config.config["exclude_tags"])):
Lists can be passed to `isdisjoint` as well, and `exclude_tags` is ensured to be a list of strings by the JSON schema already.  Is there another reason why we need the `map` here?

Besides that, I would prefer to format multiline statements this way:

```
if isinstance(obj["tags"], str) and not set(obj["tags"].split(",")).isdisjoint(
    map(str, self.config.config["exclude_tags"])
):
    continue
```

2022-03-02 21:22 UTC, peschmae commented
I've also added a test for `exclude_state` as it was missing one, and it just fit well together

2022-03-02 21:29 UTC, xoxys reviewed
Multiline formatting is a bit painful with the yapf formatter... I've added a committable suggestion to simplify it a bit.

2022-03-02 21:29 UTC, xoxys commented on prometheuspvesd/discovery.py
> +            ):
```suggestion
            if (
                isinstance(obj["tags"], str)
                and not set(obj["tags"].split(",")).isdisjoint(self.config.config["exclude_tags"])
            ):
```

2022-03-03 08:08 UTC, merged

2022-03-03 08:08 UTC, xoxys commented
Thanks again.