WIP: expose proxmox tags
thegeeklab/prometheus-pve-sd pull request #168
Opened 2022-03-10 10:18 UTC by peschmae

Initial implementation to expose the tags from proxmox to prometheus

The tags are a comma separated list (just as it is exposed by proxmox on the API), and if not present (for proxmox <6, or if none are set) it's not set

WIP because I also want to update the docs to include some examples, how to make proper use of the tags.
I've also tried to implement a test for it outside the model test, but for this to work, quite a lot of the client.get has to be mocked 

I first set it as a attribute on the host model, but I feel that this implementation, is more in line with the rest and doesn't cause an empty label if the tags are not present

2022-03-10 10:47 UTC, peschmae commented
I've checked and it seems like proxmox accepts a space as a valid character in a tag, so it would be unsave trying to use space as a separater for tags, even though the regex for tags in the relabling config, would be quite a bit nicer

2022-03-10 12:33 UTC, xoxys requested changes
Thanks a lot for your work.

2022-03-10 12:33 UTC, xoxys commented on docs/content/usage/_index.md
> +: A comma-separated list of tags, as set on Proxmox. Tags are supported by Proxmox 6+, and the field is missing if not tags are present on a vm.
Can we use `VM` instead?

2022-03-10 12:33 UTC, xoxys commented on .dictionary
> +vm
Can we use VM instead?

2022-03-10 12:33 UTC, xoxys commented on docs/content/usage/_index.md
> +: A comma-separated list of tags, as set on Proxmox. Tags are supported by Proxmox 6+, and the field is missing if not tags are present on a vm.
`if no tags are present` instead of `if not tags`

2022-03-11 09:40 UTC, xoxys commented
That's fine for now. Thanks again.

2022-03-11 09:41 UTC, merged